using System;
using System.Collections.Generic;

namespace VoxelBuild.World
{
    using VoxelBuild.Core;

    /// <summary>
    /// Describes the block texture atlas: which tile each block face uses and where the tile sits in UV space.
    /// The actual texture is generated by the rendering layer from this description.
    /// </summary>
    public static class AtlasLayout
    {
        public struct Tile
        {
            public BlockType Block;
            public Direction FaceGroup; // PosY = top, NegY = bottom, PosX = sides
            public ColorRgb Color;
            public float Noise;
            public ColorRgb Emissive;
            public SurfaceStyle Style;
            public BlockDefinition Definition;
        }

        /// <summary>Pixels across one block face.</summary>
        public const int FacePixels = 64;
        /// <summary>Each tile is twice the face size; the face maps to the inner half so mip levels stay free of neighbour bleed.</summary>
        public const int TilePixels = FacePixels * 2;
        private static readonly List<Tile> Tiles = new List<Tile>();
        private static bool initialised;

        public static int TileCount
        {
            get { EnsureInit(); return Tiles.Count; }
        }

        public static int TilesPerRow
        {
            get { EnsureInit(); return (int)Math.Ceiling(Math.Sqrt(Tiles.Count)); }
        }

        public static Tile GetTile(int index)
        {
            EnsureInit();
            return Tiles[index];
        }

        /// <summary>Fraction of the tile on each side that is padding (the face uses the inner half).</summary>
        public const float Pad = 0.25f;

        public static void GetUvRect(int tile, out float u0, out float v0, out float u1, out float v1)
        {
            EnsureInit();
            int per = TilesPerRow;
            int tx = tile % per;
            int ty = tile / per;
            float s = 1f / per;
            u0 = (tx + Pad) * s;
            v0 = (ty + Pad) * s;
            u1 = (tx + 1f - Pad) * s;
            v1 = (ty + 1f - Pad) * s;
        }

        public static void EnsureInit()
        {
            if (initialised) return;
            initialised = true;
            Tiles.Clear();
            foreach (var def in BlockRegistry.All())
            {
                if (def.Type == BlockType.Air) continue;
                def.TileTop = AddTile(def, Direction.PosY, def.TopColor);
                def.TileSide = AddTile(def, Direction.PosX, def.SideColor);
                def.TileBottom = AddTile(def, Direction.NegY, def.BottomColor);
            }
        }

        private static int AddTile(BlockDefinition def, Direction group, ColorRgb color)
        {
            Tiles.Add(new Tile
            {
                Block = def.Type, FaceGroup = group, Color = color, Noise = def.TextureNoise, Emissive = def.Emissive,
                Style = def.StyleFor(group), Definition = def,
            });
            return Tiles.Count - 1;
        }
    }
}
